#DEV POR RODRIGO CARDOSO
#ESTE SCRIPT SERVE PARA A INSTALAÇÃO AUTOMATICA DO RECURSO DE SSH
#SCRIPT UTILIZADO EM AULA PARA FINS ACADEMICOS

#!/bin/bash

#MOSTRA O IP DA MAQUINA E OUTRAS CONF DE REDE 
ip addr show

echo
echo "TECLE ENTER PARA CONTINUAR"
read pause
clear

#COMANDO PARA ALTERAR O NOME DA MAQUINA ATÉ A REINICIALIZAÇÃO
hostname RODRIGOCARDOSO
echo
echo "TECLE ENTER PARA CONTINUAR"
read pause
clear



