#DEV POR RODRIGO CARDOSO
#ESTE SCRIPT SERVE PARA A INSTALAÇÃO AUTOMATICA DO RECURSO DE SSH
#SCRIPT UTILIZADO EM AULA PARA FINS ACADEMICOS

#!/bin/bash


#COMANDO PARA VERIFICAR A VERSÃO DO SISTEMA OPERACIONAL
cat /etc/issue
echo
echo "TECLE ENTER PARA CONTINUAR"
read pause
clear

#COMANDO PARA VERIFICAR DE QUANTOS BITS É O SISTEMA 
uname -m 
echo
echo "TECLE ENTER PARA CONTINUAR"
read pause
clear 


